#!/bin/bash

# This is a thin wrapper around monetaryunit-cli that strips the Windows-style EOLs
# from the output if present. It is necessary when using monetaryunit-cli.exe on
# Linux since shells will interpret the line-endings as part of the result.

CURDIR=$(cd $(dirname "$0"); pwd)
# Get BUILDDIR and REAL_MONETARYUNITD

# Grab the value of $REAL_MONETARYUNITCLI which may be monetaryunit-cli.exe.
. "${CURDIR}/tests-config.sh"

"${REAL_MONETARYUNITCLI}" "$@" | sed 's/\r//'
